version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:11.0.3
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=admin'