version: "3"
services:
  localhost:
    image: mongo:4.4.1
    container_name: trackmapi_mongodb

  trackmapi:
    image: bananatigeer/trackmapi:$BUILD_NUMBER
    container_name: trackmapi
    ports:
      - 8081:8081
    depends_on:
      - localhost
    links:
      - localhost